#!/bin/sh
# Makes temporary installation and runs installcheck-world on it
# Should be run as non-privileged user.
# Exit on all errors
# If run without arguments, makes installcheck-world
# Otherwise first argument is interpreted as subdirectory 
# to change before runnning make installchedk
# i.e
#    run_install_check . 
# test core only
#    run_install_check contrib
# tests contrib only
# etc.
# All other arguments are passed to Makefile intact
# To make possible pass arguments to installcheck-world
#    run_install_check world
# does the same as no args
set -e
# Install
make install prefix=`pwd`/tmp_install
make install prefix=`pwd`/tmp_install -C contrib

# Setup an environment
LD_LIBRARY_PATH=$(pwd)/tmp_install/lib
PATH=$(pwd)/tmp_install/bin:${PATH}
PGDATA=$(pwd)/tmp_base
export LD_LIBRARY_PATH PATH PG_DATA

# create installation
PGPORT=`./.ci/find_free_port 5432`
export PGPORT
./.ci/make_test_base $PGDATA
#run checks
set +e
if [  -z "$1" -o "$1" = "world" ]; then
make installcheck-world  prefix=`pwd`/tmp_install NO_LOCALE=1
else
dir=$1
shift
make -C "$dir" installcheck prefix=`pwd`/tmp_install NO_LOCALE=1 ${@:+"$@"}
fi
code=$?
pg_ctl stop -D $PGDATA
exit $code
