# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  nhosts = 3

  nhosts.times do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.hostname = "node#{i}"
      if i == nhosts - 1
        node.vm.provision :ansible do |ansible|
          ansible.limit = "all"
          ansible.playbook = "provision.yml"
        end
      end
    end
  end

end

