script = <<SCRIPT
#!/bin/bash -e

if [ ! -f /etc/default/docker ]; then
  echo "/etc/default/docker not found -- is docker installed?" >&2
  exit 1
fi

apt-get -y install python-pip python-virtualenv
apt-get -y install postgresql-server-dev-all python-dev

cd /vagrant

export PIP_DOWNLOAD_CACHE=/vagrant/.pip_download_cache

SCRIPT

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.provider :virtualbox do |vb, override|
    vb.memory = 2048
  end

  # there are obviously vagrant versions with a
  # broken 'docker' provisioner that can be fixed
  # by invoking an 'apt-get update' *before* docker itself
  config.vm.provision "shell", inline: "apt-get update"

  # fetch the ubuntu:latest image that is required for
  # the test suite
  config.vm.provision "docker", images: ["ubuntu:trusty"]

  # kick off the tests automatically
  config.vm.provision "shell", inline: script
end

