# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", type: "dhcp"

  nhosts = 3

  nhosts.times do |i|
    config.vm.define "node#{i}" do |node|
      #node.vm.network "private_network", ip: "10.20.30.#{i+40}"
      node.vm.hostname = "node#{i}"
      if i == nhosts - 1
        node.vm.provision :ansible do |ansible|
          ansible.limit = "all"
          ansible.playbook = "provision.yml"
        end
      end
    end
  end

end

