CREATE TABLE abc(id SERIAL)
PARTITION BY RANGE(id) INTERVAL (100)
(
  PARTITION abc_1 VALUES LESS THAN (100),
  PARTITION abc_2 VALUES LESS THAN (200)
);

ALTER TABLE abc ADD PARTITION abc_3 VALUES LESS THAN (400);
ALTER TABLE abc SPLIT PARTITION abc_3 AT (300) INTO (PARTITION abc_3, PARTITION abc_4);
ALTER TABLE abc MERGE PARTITIONS abc_3, abc_4 INTO PARTITION abc_3;
